info:
  app:
    name: api-gateway
    description: Zuul API Gateway
    version: 1.0.0-SNAPSHOT
# Define the port where the API gateway server would be running
server:
  port: 8765
  contextPath:
zuul:
  sensitive-headers: Authorization
  ignoredServices: '*'
  routes:
    user:
      path: /user/**
      url: http://ec2-54-87-196-13.compute-1.amazonaws.com/auth/realms/Zuul/protocol/openid-connect/userinfo
    device-service:
      path: /device-service/**
      serviceId: device-service
      stripPrefix: false
    reservation-service:
      path: /reservation-service/**
      serviceId: reservation-service
      stripPrefix: false
    upload-service:
      path: /upload-service/**
      serviceId: upload-service
      stripPrefix: false
spring:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      accessTokenUri: http://ec2-54-87-196-13.compute-1.amazonaws.com/auth/realms/haystack/protocol/openid-connect/token
      userAuthorizationUri: http://ec2-54-87-196-13.compute-1.amazonaws.com/auth/realms/haystack/protocol/openid-connect/auth
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://ec2-54-87-196-13.compute-1.amazonaws.com/auth/realms/Zuul/protocol/openid-connect/userinfo
