endpoints:
  actuator:
    enabled: true
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
management:
  security:
    enabled: false
spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
    rest:
      base-path: /api
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    config:
      uri: http://config-server:8888
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true
        register-health-check: true
        register: true
        fail-fast: false
        health-check-path:  ${server.contextPath}/health
      config:
        enabled: true
haystack:
  hostname: haystack-lb-764465164.us-east-1.elb.amazonaws.com
keycloak:
  realm: haystack
  auth-server-url:  http://${haystack.hostname}/auth
  use-resource-role-mappings: true
  principal-attribute: preferred_username
  enable-basic-auth: false
  enabled: true
  ssl-required: external # no ssl is ok for demo  - do not use this in production
