logging:
  level:
    org:
      springframework:
        security: ERROR
        data: DEBUG
    com:
      samsung:
        haystack: DEBUG
      netflix:
        zuul: ERROR
endpoints:
  actuator:
    enabled: true
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
management:
  security:
    enabled: false
spring:
  cloud:
    config:
      uri: http://localhost:8888
    consul:
      discovery:
        enabled: true
        register-health-check: true
        register: true
        fail-fast: false
        health-check-path:  ${server.contextPath}/health
      config:
        enabled: true