info:
  app:
    name: Devices Web Service
    description: RestFul Application Holding Devices
    version: 1.0-SNAPSHOT
server:
  port: 8086
  contextPath: /device-service
spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: devices