info:
  app:
    name: Reservations  Service
    description: RestFul Application Holding Reservations for Devices
    version: 1.0-SNAPSHOT
server:
  port: 8087
  contextPath: /reservation-service
spring:
  application:
    name: reservation-service
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: reservations
keycloak:
  enabled: true
  enable-basic-auth: false
  realm: haystack
  auth-server-url:  http://10.0.75.1:8080/auth
  ssl-required: external # no ssl is ok for demo  - do not use this in production
  public-client: false # we do not write a web-app - so no login page and redirects are necessary
  resource: reservation-service
  bearer-only: true  # authentication via accesstoken is fine
  credentials:
    secret: 29899d5a-ff06-42a6-a8e7-3b055b0cc875
  use-resource-role-mappings: true