info:
  app:
    name: Reservations  Service
    description: RestFul Application Holding Reservations for Devices
    version: 1.0-SNAPSHOT
server:
  port: 8087
  contextPath: /reservation-service
spring:
  application:
    name: reservation-service
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: reservations
keycloak:
  resource: reservation-service
  credentials:
    secret: 29899d5a-ff06-42a6-a8e7-3b055b0cc875
