info:
  app:
    name: Upload Service
    description: RestFul Application Storing User APK's
    version: 1.0.0-SNAPSHOT
server:
  port: 8088
  contextPath: /upload-service
spring:
  data:
    mongodb:
      database: user-apks
  http:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
keycloak:
  resource: upload-service
  credentials:
    secret: 9c05d3f9-b8af-400d-9876-9173db088c15
  public-client: false # we do not write a web-app - so no login page and redirects are necessary
  bearer-only: true  # authentication via accesstoken is fine
