info:
  app:
    name: Upload Service
    description: RestFul Application Storing User APK's
    version: 1.0.0-SNAPSHOT
server:
  port: 8088
  contextPath: /upload-service
spring:
  application:
    name: upload-service
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: user-apks
keycloak:
  enabled: true
  enable-basic-auth: false
  realm: haystack
  auth-server-url:  http://ec2-54-87-196-13.compute-1.amazonaws.com/auth
  ssl-required: external # no ssl is ok for demo  - do not use this in production
  public-client: false # we do not write a web-app - so no login page and redirects are necessary
  resource: upload-service
  bearer-only: true  # authentication via accesstoken is fine
  credentials:
    secret: 9c05d3f9-b8af-400d-9876-9173db088c15
  use-resource-role-mappings: true
  principal-attribute: preferred_username
